VinaC2C.MVC/Controllers/FeatureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using VinaC2C.Data.Context;
using VinaC2C.Data.Models;
using VinaC2C.Data.Services;
using VinaC2C.MVC.Models;
using VinaC2C.MVC.ServerHub;
using VinaC2C.Ultilities.AppInfor;
using VinaC2C.Ultilities.Enums;
using VinaC2C.Ultilities.Extensions;

namespace VinaC2C.MVC.Controllers
{
    [Authorize]
    public class FeatureController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        private readonly VinaC2CContext _context;

        public FeatureService featureService;


        private IHubContext<SignalServer> _hubContext;

        public FeatureController(VinaC2CContext context, IWebHostEnvironment environment, IHubContext<SignalServer> hubContext)
        {
            this._context = context;
            this._environment = environment;
            this._hubContext = hubContext;
            featureService = new FeatureService(context);
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public async Task<JsonResult> GetAllAsyncToList()
        {
            return Json(await featureService.GetAllToListAsync());
        }

        public JsonResult Create(Feature feature)
        {
            feature.Initialization(ObjectInitType.Insert, "", HttpContext);
            int result = featureService.Create(feature);
            _hubContext.Clients.All.SendAsync("dataChangeNotification", null);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.InsertSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.InsertFailMessage });
        }

        public JsonResult Update(Feature feature)
        {
            feature.Initialization(ObjectInitType.Update, "", HttpContext);
            int result = featureService.Update(feature.Id, feature);
            _hubContext.Clients.All.SendAsync("dataChangeNotification", null);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.UpdateFailMessage });
        }

        public JsonResult Delete(Feature feature)
        {
            int result = featureService.Delete(feature.Id);
            _hubContext.Clients.All.SendAsync("dataChangeNotification", null);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.DeleteSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.DeleteFailMessage });
        }


        public async Task<IActionResult> GetMenuLeft()
        {
            var features = await featureService.GetAllToListAsync();
            var menu = features.OrderBy(item => item.SortOrder).GenerateTree(item => item.Id, item => item.ParentFeatureID);
            return PartialView("~/Views/Partial/_MenuLeft.cshtml", menu);
        }
    }
}

VinaC2C.MVC/Controllers/FeatureRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using VinaC2C.Data.Context;
using VinaC2C.Data.DataTransferObject;
using VinaC2C.Data.Models;
using VinaC2C.Data.Services;
using VinaC2C.MVC.Models;
using VinaC2C.MVC.ServerHub;
using VinaC2C.Ultilities.AppInfor;
using VinaC2C.Ultilities.Enums;
using VinaC2C.Ultilities.Extensions;

namespace VinaC2C.MVC.Controllers
{
    [Authorize]
    public class FeatureRoleController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        private readonly VinaC2CContext _context;

        public FeatureRoleService featureRoleService;
        public UserService userService;


        private IHubContext<SignalServer> _hubContext;

        public FeatureRoleController(VinaC2CContext context, IWebHostEnvironment environment, IHubContext<SignalServer> hubContext)
        {
            this._context = context;
            this._environment = environment;
            this._hubContext = hubContext;
            featureRoleService = new FeatureRoleService(context);
            userService = new UserService(context);

        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = new FeatureRoleModel();
            model.users = await userService.GetForSelectList();
            model.userOptions = new SelectList(model.users, nameof(UserSelect.ID), nameof(UserSelect.DisplayName));
            return View(model);
        }
        
        public async Task<JsonResult> GetAllAsyncToList()
        {
            return Json(await featureRoleService.GetAllToListAsync());
        }

        public JsonResult Create(FeatureRole featureRole, Int64 UserID)
        {
            featureRole.Initialization(ObjectInitType.Insert, "",HttpContext);
            int result = featureRoleService.Create(featureRole);
            _hubContext.Clients.All.SendAsync("dataChangeNotification", null);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.InsertSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.InsertFailMessage });
        }

        public JsonResult Update(FeatureRole featureRole)
        {
            if(featureRole.Id != 0)
            {
                featureRole.Initialization(ObjectInitType.Update, "", HttpContext);
                int result = featureRoleService.Update(featureRole.Id, featureRole);
                _hubContext.Clients.All.SendAsync("dataChangeNotification", null);
                if (result != 0)
                    return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
                else
                    return Json(new { messageType = "error", note = AppGlobal.UpdateFailMessage });
            }
            return Json(new { messageType = "info", note = AppGlobal.UpdateLocalMessage });
        }

        public JsonResult Delete(FeatureRole featureRole)
        {
            int result = featureRoleService.Delete(featureRole.Id);
            _hubContext.Clients.All.SendAsync("dataChangeNotification", null);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.DeleteSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.DeleteFailMessage });
        }

        public JsonResult GetFeatureByUserID(int UserID)
        {
            return Json(featureRoleService.GetFeatureByUserID(UserID));
        }

        public JsonResult GetFeatureByUsername(string username)
        {
            return Json(featureRoleService.GetFeatureByUsername(username));
        }

        public JsonResult InitializeUserFeatureRole(Int64 UserID)
        {
            return Json(featureRoleService.InitializeUserFeatureRole(UserID));
        }

        public JsonResult SaveChange(List<UserFeatureRole> userFeatureRoles = null, bool isAllowAll = false)
        {
            var featureRoles = userFeatureRoles.Select(item =>
            {
                var newFeatureRole = new Data.Models.FeatureRole
                {
                    FeatureID = item.FeatureID,
                    UserID = item.UserID,
                    IsAllow = item.IsAllow ? true : isAllowAll
                };
                newFeatureRole.Initialization(ObjectInitType.Insert, "", HttpContext);
                return newFeatureRole;
            }).ToList();
            int result = featureRoleService.SaveChange(featureRoles);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.UpdateFailMessage });
        }
    }
}

VinaC2C.MVC/Views/FeatureRole/Index.cshtml
@{
    ViewData["Title"] = "Phân Quyền Tính Năng";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}
@model VinaC2C.MVC.Models.FeatureRoleModel;
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Phân Quyền Tính Năng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang Chủ</a></li>
                    <li class="breadcrumb-item active">Phân Quyền Tính Năng</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="card">
        <div class="card-header container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-sm-12 mt-1">
                        <select id="UserID" class="form-control select2bs4" asp-for="@Model.UserID" asp-items="@Model.userOptions"></select>
                    </div>

                    <div class="col-md-8 col-sm-12 mt-1">
                        <div class="d-flex justify-content-between align-items-center">
                            <button id="searchButton" type="button" class="btn btn-success btn-large" style="flex-basis:20%;" onclick="onSearchUserFeatureRole()">
                                <i class="fas fa-search h5 m-0 p-0"></i>
                            </button>
                            <button id="initButton" type="button" class="btn btn-primary btn-large" style="flex-basis:20%;" onclick="onInitFeatureRole()">
                                <i class="fas fa-file-upload h5 m-0 p-0"></i>
                            </button>
                            <div style="flex-basis:35%;">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="checkboxPrimary3" class="isAllowAll">
                                    <label for="checkboxPrimary3">
                                        Tất Cả
                                    </label>
                                </div>
                            </div>
                            <button id="initButton" type="button" class="btn btn-primary btn-large" style="flex-basis:20%;" onclick="onSaveChange()">
                                <i class="fas fa-save h5 m-0 p-0"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <h3 class="card-title mt-2">Danh Sách Tính Năng</h3>
                </div>
            </div>
        </div>
        <div class="card-body" style="height:700px;">
            <div id="listFeatureRole" style="height:700px;"></div>
        </div>
    </div>
</section>

<script src="~/LTEplugins/jsgrid/jsgrid.min.js"></script>
<script src="~/LTEplugins/select2/js/select2.full.min.js"></script>
<script>

    let featureRoles = [];
    let features = [];

    $(document).ready(() => {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        });

        $("#UserID").on('change', () => {
            $("#searchButton").trigger('click');
        });

        $.ajax({
            url: "@Url.Action("GetAllAsyncToList","Feature")",
            success: (respone) => {
                console.log(respone);
                features = respone;
            }
        }).done(() => {
            renderGrid();
        });

    });

    function renderGrid() {
        $("#listFeatureRole").jsGrid({
            height: "100%",
            width: "100%",
            paging: true,
            pagerFormat: "Trang: {first} {prev} {pages} {next} {last}    {pageIndex} of {pageCount}",
            pagePrevText: "Trước",
            pageNextText: "Tiếp",
            pageNavigatorNextText: "...",
            pageNavigatorPrevText: "...",
            editing: true,
            autoload: true,
            data: featureRoles,
            inserting: true,
            deleteConfirm: "Bạn Có Chắc Muốn Xóa",
            reloadAfterSubmit: true,
            pageSize: 15,
            pageButtonCount: 5,
            controller: {
                insertItem: function (item) {
                    item.UserID = $("#UserID").children("option:selected").val();
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Create","FeatureRole")',
                        data: {
                            featureRole: item,
                            UserID: $("#UserID").children("option:selected").val()
                        },
                    }).done(function (respone) {
                        console.log(respone);
                        $.notify(respone.note, respone.messageType);
                    });
                },
                updateItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Update","FeatureRole")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $.notify(respone.note, respone.messageType);
                    });
                },
                deleteItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete","FeatureRole")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $.notify(respone.note, respone.messageType);
                    });
                }
            },

            fields: [
                { name: "id", type: "number", title: "Id", with: 100, editing: false, inserting: false },
                { name: "featureID", type: "select", title: "Tên Chức Năng", items: features, valueField: "id", textField: "name", with:300 },
                { name: "isAllow", type: "checkbox", title:"Truy Cập" , with:300 },
                { type: "control" }
            ]
        });
    }

    function onInitFeatureRole() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("InitializeUserFeatureRole","FeatureRole")',
            data: {
                 UserID: $("#UserID").children("option:selected").val()
            },
            success: (respone) => {
                featureRoles = respone;
                console.log(featureRoles);
                renderGrid();
            }
        });
    }

    function onSearchUserFeatureRole() {
         $.ajax({
            type: 'GET',
            url: '@Url.Action("GetFeatureByUserID","FeatureRole")',
            data: {
                UserID: $("#UserID").children("option:selected").val(),
            },
            success: (respone) => {
                featureRoles = respone;
                console.log(featureRoles);
                renderGrid();
            }
        });
    }

    function onSaveChange() {
        console.log(document.getElementById('checkboxPrimary3').checked);
        $.ajax({
            type: 'POST',
            datatype: "JSON",
            url: '@Url.Action("SaveChange","FeatureRole")',
            data: {
                userFeatureRoles: featureRoles,
                isAllowAll: document.getElementById('checkboxPrimary3').checked,
            },
            success: (respone) => {
                featureRoles = respone;
                console.log(featureRoles);
                $("#searchButton").trigger('click');
            }
        });
    }
</script>