VinaC2C.MVC/Controllers/DigitalShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using VinaC2C.Data.Context;
using VinaC2C.Data.Models;
using VinaC2C.Data.Services;
using VinaC2C.Ultilities.AppInfor;
using VinaC2C.Ultilities.Enums;


namespace VinaC2C.MVC.Controllers
{
    public class DigitalShopController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        private readonly VinaC2CContext _context;

        public DigitalShopService digitalShopService;

        public DigitalShopController(VinaC2CContext context, IWebHostEnvironment environment)
        {
            this._context = context;
            this._environment = environment;
            digitalShopService = new DigitalShopService(context);
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public async Task<JsonResult> GetAllAsyncToList()
        {
            return Json(await digitalShopService.GetAllToListAsync());
        }

        public JsonResult Create(DigitalShop shop)
        {
            shop.Initialization(ObjectInitType.Insert, "", HttpContext);
            int result = digitalShopService.Create(shop);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.InsertSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.InsertFailMessage });
        }

        public JsonResult Update(DigitalShop shop)
        {
            shop.Initialization(ObjectInitType.Update, "", HttpContext);
            int result = digitalShopService.Update(shop.Id, shop);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.UpdateFailMessage });
        }

        public JsonResult Delete(DigitalShop shop)
        {
            int result = digitalShopService.Delete(shop.Id);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.DeleteSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.DeleteFailMessage });
        }
    }
}

VinaC2C.MVC/Controllers/DigitalShopRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using VinaC2C.Data.Context;
using VinaC2C.Data.DataTransferObject;
using VinaC2C.Data.Models;
using VinaC2C.Data.Services;
using VinaC2C.MVC.Models;
using VinaC2C.Ultilities.AppInfor;
using VinaC2C.Ultilities.Enums;


namespace VinaC2C.MVC.Controllers
{
    public class DigitalShopRoleController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        private readonly VinaC2CContext _context;

        public DigitalShopRoleService digitalShopRoleService;
        
        public UserService userService;

        public DigitalShopRoleController(VinaC2CContext context, IWebHostEnvironment environment)
        {
            this._context = context;
            this._environment = environment;
            digitalShopRoleService = new DigitalShopRoleService(context);
            userService = new UserService(context);
        }

        public async Task<IActionResult> Index()
        {
            var model = new DigitalShopRoleModel();
            model.users = await userService.GetForSelectList();
            model.userOptions = new SelectList(model.users, nameof(UserSelect.ID), nameof(UserSelect.DisplayName));
            return View(model);
        }
        
        public async Task<JsonResult> GetAllAsyncToList()
        {
            return Json(await digitalShopRoleService.GetAllToListAsync());
        }

        public JsonResult Create(DigitalShopRole role)
        {
            role.Initialization(ObjectInitType.Insert, "");
            int result = digitalShopRoleService.Create(role);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.InsertSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.InsertFailMessage });
        }

        public JsonResult Update(DigitalShopRole role)
        {
            if(role.Id != 0)
            {
                role.Initialization(ObjectInitType.Update, "");
                int result = digitalShopRoleService.Update(role.Id, role);
                if (result != 0)
                    return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
                else
                    return Json(new { messageType = "error", note = AppGlobal.UpdateFailMessage });
            }
            return Json(new { messageType = "info", note = AppGlobal.UpdateLocalMessage });
        }

        public JsonResult Delete(DigitalShopRole role)
        {
            int result = digitalShopRoleService.Delete(role.Id);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.DeleteSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.DeleteFailMessage });
        }

        public JsonResult GetDigitalShopByUserID(int UserID)
        {
            return Json(digitalShopRoleService.GetDigitalShopByUserID(UserID));
        }

        public JsonResult GetDigitalShopByUsername(string username)
        {
            return Json(digitalShopRoleService.GetDigitalShopByUsername(username));
        }

        public JsonResult InitializeUserDigitalShopRole(Int64 UserID)
        {
            return Json(digitalShopRoleService.InitializeUserDigitalShopRole(UserID));
        }

        public JsonResult SaveChange(List<UserDigitalShopRole> userĐigitalShopRoles = null, bool isAllowAll = false)
        {
            var digitalShopRoles = userĐigitalShopRoles.Select(item =>
            {
                var newDigitalShopRole = new Data.Models.DigitalShopRole
                {
                    DigitalShopID = item.DigitalShopID,
                    UserID = item.UserID,
                    IsAllow = item.IsAllow ? true : isAllowAll
                };
                newDigitalShopRole.Initialization(ObjectInitType.Insert, "", HttpContext);
                return newDigitalShopRole;
            }).ToList();
            int result = digitalShopRoleService.SaveChange(digitalShopRoles);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
            else
                return Json(new { messageType = "error", note = AppGlobal.UpdateFailMessage });
        }
    }
}

VinaC2C.MVC/Views/DigitalShopRole/Index.cshtml
@{
    ViewData["Title"] = "Phân Quyền Sàn Thương Mại";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}
@model VinaC2C.MVC.Models.DigitalShopRoleModel;
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Phân Quyền Cửa Hàng</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang Chủ</a></li>
                    <li class="breadcrumb-item active">Phân Quyền Sàn Thương Mại</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="card">
        <div class="card-header container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-4 col-sm-12 mt-1">
                        <select id="UserID" class="form-control select2bs4" asp-for="@Model.UserID" asp-items="@Model.userOptions"></select>
                    </div>

                    <div class="col-md-8 col-sm-12 mt-1">
                        <div class="d-flex justify-content-between align-items-center">
                            <button id="searchButton" type="button" class="btn btn-success btn-large" style="flex-basis:20%;" onclick="onSearchUserDigitalShopRole()">
                                <i class="fas fa-search h5 m-0 p-0"></i>
                            </button>
                            <button id="initButton" type="button" class="btn btn-primary btn-large" style="flex-basis:20%;" onclick="onInitDigitalShopRole()">
                                <i class="fas fa-file-upload h5 m-0 p-0"></i>
                            </button>
                            <div style="flex-basis:35%;">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="checkboxPrimary3">
                                    <label for="checkboxPrimary3">
                                        Tất Cả
                                    </label>
                                </div>
                            </div>
                            <button id="initButton" type="button" class="btn btn-primary btn-large" style="flex-basis:20%;" onclick="onSaveChange()">
                                <i class="fas fa-save h5 m-0 p-0"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card">
        <div class="card-header container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <h3 class="card-title mt-2">Danh Sách Cửa Hàng</h3>
                </div>
            </div>
        </div>
        <div class="card-body" style="height:700px;">
            <div id="listDigitalShopRole" style="height:700px;"></div>
        </div>
    </div>
</section>

<script src="~/LTEplugins/jsgrid/jsgrid.min.js"></script>
<script src="~/LTEplugins/select2/js/select2.full.min.js"></script>
<script>

    let digitalShopRoles = [];
    let digitalShops = [];

    $(document).ready(() => {
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        });

        $("#UserID").on('change', () => {
            $("#searchButton").trigger('click');
        });

        $.ajax({
            url: "@Url.Action("GetAllAsyncToList","DigitalShop")",
            success: (respone) => {
                console.log(respone);
                digitalShops = respone;
            }
        }).done(() => {
            renderGrid();
        });
    });

    function renderGrid() {
        $("#listDigitalShopRole").jsGrid({
            height: "100%",
            width: "100%",
            paging: true,
            pagerFormat: "Trang: {first} {prev} {pages} {next} {last}    {pageIndex} of {pageCount}",
            pagePrevText: "Trước",
            pageNextText: "Tiếp",
            pageNavigatorNextText: "...",
            pageNavigatorPrevText: "...",
            editing: true,
            autoload: true,
            data: digitalShopRoles,
            inserting: true,
            deleteConfirm: "Bạn Có Chắc Muốn Xóa",
            reloadAfterSubmit: true,
            pageSize: 15,
            pageButtonCount: 5,
            controller: {
                insertItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Create","DigitalShopRole")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $.notify(respone.note, respone.messageType);
                        $("#searchButton").trigger('click');
                    });
                },
                updateItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Update","DigitalShopRole")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $.notify(respone.note, respone.messageType);
                    });
                },
                deleteItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete","DigitalShopRole")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $.notify(respone.note, respone.messageType);
                        $("#searchButton").trigger('click');
                    });
                }
            },

            fields: [
                { name: "id", type: "number", title: "Id", with: 100, editing: false, inserting: false },
                { name: "digitalShopID", type: "select", title: "Shop Thương Mại Điện Tử", items: digitalShops, valueField: "id", textField: "name", with:300 },
                { name: "isAllow", type: "checkbox", title:"Truy Cập" , with:300 },
                { type: "control" }
            ]
        });
    }

    function onSearchUserDigitalShopRole() {
         $.ajax({
            type: 'GET',
            url: '@Url.Action("GetDigitalShopByUserID","DigitalShopRole")',
            data: {
                UserID: $("#UserID").children("option:selected").val(),
            },
            success: (respone) => {
                digitalShopRoles = respone;
                console.log(digitalShopRoles);
                renderGrid();
            }
        });
    }

    function onInitDigitalShopRole() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("InitializeUserDigitalShopRole","DigitalShopRole")',
            data: {
                UserID: $("#UserID").children("option:selected").val()
            },
            success: (respone) => {
                digitalShopRoles = respone;
                console.log(digitalShopRoles);
                renderGrid();
            }
        });
    }

    function onSaveChange() {
        console.log(document.getElementById('checkboxPrimary3').checked);
        $.ajax({
            type: 'POST',
            datatype: "JSON",
            url: '@Url.Action("SaveChange","DigitalShopRole")',
            data: {
                userDigitalShopRoles: digitalShopRoles,
                isAllowAll: document.getElementById('checkboxPrimary3').checked,
            },
            success: (respone) => {
                serviceTicketRoles = respone;
                console.log(serviceTicketRoles);
                $("#searchButton").trigger('click');
            }
        });
    }
</script>