VinaC2C.MVC/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using VinaC2C.Data.Context;
using VinaC2C.Data.Models;
using VinaC2C.Data.Services;
using VinaC2C.Ultilities.AppInfor;
using VinaC2C.Ultilities.Enums;


namespace VinaC2C.MVC.Controllers
{
    [Authorize]
    public class UnitController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        private readonly VinaC2CContext _context;

        public UnitService unitService;

        public UnitController(VinaC2CContext context, IWebHostEnvironment environment)
        {
            this._context = context;
            this._environment = environment;
            unitService = new UnitService(context);
        }

        public IActionResult Index()
        {
            return View();
        }
        
        public async Task<JsonResult> GetAllAsyncToList()
        {
            return Json(await unitService.GetAllToListAsync());
        }

        public JsonResult Create(Unit unit)
        {
            unit.Initialization(ObjectInitType.Insert, "", HttpContext);
            int result = unitService.Create(unit);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.InsertSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.InsertFailMessage });
        }

        public JsonResult Update(Unit unit)
        {
            unit.Initialization(ObjectInitType.Update, "", HttpContext);
            int result = unitService.Update(unit.Id, unit);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.UpdateFailMessage });
        }

        public JsonResult Delete(Unit unit)
        {
            int result = unitService.Delete(unit.Id);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.DeleteSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.DeleteFailMessage });
        }
    }
}

VinaC2C.MVC/Controllers/UnitConvertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using VinaC2C.Data.Context;
using VinaC2C.Data.Models;
using VinaC2C.Data.Services;
using VinaC2C.Ultilities.AppInfor;
using VinaC2C.Ultilities.Enums;


namespace VinaC2C.MVC.Controllers
{
    [Authorize]
    public class UnitConvertController : Controller
    {
        private readonly IWebHostEnvironment _environment;

        private readonly VinaC2CContext _context;

        public UnitConvertService unitConvertService;

        public UnitConvertController(VinaC2CContext context, IWebHostEnvironment environment)
        {
            this._context = context;
            this._environment = environment;
            unitConvertService = new UnitConvertService(context);
        }

        public IActionResult Index()
        {
            return View();
        }

        #region Default
        public async Task<JsonResult> GetAllAsyncToList()
        {
            return Json(await unitConvertService.GetAllToListAsync());
        }

        public JsonResult Create(UnitConvert unitConvert)
        {
            unitConvert.Initialization(ObjectInitType.Insert, "", HttpContext);
            int result = unitConvertService.Create(unitConvert);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.InsertSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.InsertFailMessage });
        }

        public JsonResult Update(UnitConvert unitConvert)
        {
            unitConvert.Initialization(ObjectInitType.Update, "", HttpContext);
            int result = unitConvertService.Update(unitConvert.Id, unitConvert);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.UpdateSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.UpdateFailMessage });
        }

        public JsonResult Delete(UnitConvert unitConvert)
        {
            int result = unitConvertService.Delete(unitConvert.Id);
            if (result != 0)
                return Json(new { messageType = "success", note = AppGlobal.DeleteSuccessMessage });
            else
                return Json(new { messageType = "eror", note = AppGlobal.DeleteFailMessage });
        }
        #endregion
    }
}

VinaC2C.MVC/Views/UnitConvert/Index.cshtml
@{
    ViewData["Title"] = "Bảng Đơn Vị Tính";
    Layout = "~/Views/Shared/_AdminLTELayout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Hệ Thống Chuyển Đổi Đơn Vị</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Cấu Hình</a></li>
                    <li class="breadcrumb-item active">Chuyển Đổi Đơn Vị</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="card">
        <div class="card-header container-fluid">
            <div class="container-fluid">
                <div class="row">
                    <h3 class="card-title col-8 col-md-11 m-0 p-0 mt-2">Danh Mục Đơn Vị Tính</h3>
                    <button id="reloadButton" type="button" class="btn btn-success col-4 col-md-1" onclick="onReloadGrid('listUnitConvert')">
                        <i class="fas fa-sync-alt h5 m-0 p-0"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="card-body" style="height:700px;">
            <div id="listUnitConvert" style="height:700px;"></div>
        </div>
    </div>
</section>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="~/LTEplugins/jsgrid/jsgrid.min.js"></script>
<script>

    let units = [];

    $(document).ready(() => {
        $.ajax({
            url: "@Url.Action("GetAllAsyncToList","Unit")",
            success: (respone) => {
                console.log(respone);
                units = respone;
                renderGrid();
            }
        });
    });

    function renderGrid() {
        $("#listUnitConvert").jsGrid({
            height: "100%",
            width: "100%",
            paging: true,
            filtering: true,
            autoload: true,
            pagerFormat: "Trang: {first} {prev} {pages} {next} {last}    {pageIndex} of {pageCount}",
            pagePrevText: "Trước",
            pageNextText: "Tiếp",
            pageNavigatorNextText: "...",
            pageNavigatorPrevText: "...",
            editing: true,
            inserting: true,
            reloadAfterSubmit: true,
            pageSize: 20,
            pageButtonCount: 5,
            loadMessage: "Đang Tải....",
            controller: {
                loadData: function() {
                    var d = $.Deferred();
                    $.ajax({
                        type:"GET",
                        url: '@Url.Action("GetAllAsyncToList","UnitConvert")'
                    }).done(function (response) {
                        console.log(response);
                        d.resolve(response);
                    });
                    return d.promise();
                },
                insertItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Create","UnitConvert")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $(this).jqGrid().trigger('reloadGrid');
                    });
                },
                updateItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Update","UnitConvert")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $(this).jqGrid().trigger('reloadGrid');
                    });
                },
                deleteItem: function (item) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete","UnitConvert")',
                        data: item
                    }).done(function (respone) {
                        console.log(respone);
                        $(this).jqGrid().trigger('reloadGrid');
                    });
                }
            },

            fields: [
                
                { name: "sourceUnit", type: "select", items:units, valueField: "id", textField: "name", title:"Từ Đơn Vị" , with:300 },
                { name: "sourceCoefficient", type: "number", title: "Hệ Số", with: 200 },
                { name: "destinationUnit", type: "select", items:units, valueField: "id", textField: "name", title: "Dến Đơn Vị", with: 200 },
                { name: "destinationCoefficient", type: "text", title: "Hệ Số", with: 200 },
                { type: "control" }
            ]
        });
    }

    function getUnits() {
        $.ajax({
            url: "@Url.Action("GetAllAsyncToList","Unit")",
            success: (respone) => {
                console.log(respone);
                units = respone;
            }
        });
    }
</script>